server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  port: 8901
  servlet:
    context-path: /kappa-talk
spring:
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB:}
      database: ${MONGO_DB:}
      uri: ${MONGO_CONNECTION_URL:}
  banner:
    location: banner.txt

custom:
  hazelcast-hosts: localhost
  http-port: 8900
  https-port: 8901
  security-policy: NONE
  connector-scheme: http
  auth-service: http://localhost:8081/lambda-auth/oauth/check_token

logging:
  config: classpath:log4j-spring.xml

