hazelcast:
    hosts: 172.18.0.2,172.18.0.3,172.18.0.4
server:
    compression:
        enabled: true
        mime-types: server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024
    http:
        port: 8080
    http2:
        enabled: true
    https:
        port: 8081
    port: 8901
    servlet:
        context-path: /vengeance
    ssl:
        enabled: true
        enabled-protocols: ${SSL_ENABLED_PROTOCOLS:}
        key-alias: ${SSL_KEY_ALIAS:}
        key-password: ${SSL_KEY_PASSWORD:}
        key-store: ${SSL_KEYSTORE_PATH:}
        key-store-password: ${SSL_KEYSTORE_PASSWORD:}
        key-store-type: ${SSL_KEYSTORE_TYPE:}
        protocol: ${SSL_PROTOCOL:}
spring:
    data:
        mongodb:
            authentication-database: ${MONGO_AUTH_DB:}
            database: ${MONGO_DB:}
            uri: ${MONGO_CONNECTION_URL:}
